### ISSUE TITLE
translate plan of chinese

### ISSUE THREAD

**Issue by chinanf-boy** [ronami/minipack#2]
https://github.com/chinanf-boy/minipack-explain

**Comment by ronami** [comment]
Wow! Thank you for the translation @chinanf-boy! 🎉 

I'm super happy to have this project available in other languages. Do you think you can create a pull-request with the translation? We can then link to it from the main README.md.

Also, I really like the concept of having comments inside the code that explain what it is trying to achieve. Do you think you can help with translating [src/minipack.js](https://github.com/ronami/minipack/blob/master/src/minipack.js) and [README.md](https://github.com/ronami/minipack/blob/master/README.md) into Chinese? We can have a `translations` directory with a folder for every language. Every language directory will have it’s own translated `minipack.js` and `README.md` files.

What do you think?

Thank you 🙂

**Comment by chinanf-boy** [comment]
### you want me to do List

---

- [ ] check?

#### 1. link to it from the main README.md. 

yes, I will add link in readme.md

<details>

<summary>new look with `readme.md` like this</summary> 

### Cool, where do I start?

Head on to the source code: [src/minipack.js](src/minipack.js).

|other language |
|---|
|[中文](https://github.com/chinanf-boy/minipack-explain)|

</details>


> #6 

---

- [✅] check?

### 2. comments inside the code

yes, later I will add this way to `src/minipack.js` and `readme.md` in my `minipack-explain`

https://github.com/chinanf-boy/minipack-explain/blob/master/minipack.js

> ⚠️, but `We can have a translations directory with a folder for every language` 

> That means ➡️ 

I also pull-request the chinese  `src/minipack.js` and `readme.md`

to your `minipack/translations ` ❓

- [ ] Is ❓

---

### And

Allow me add your project link to my project https://github.com/chinanf-boy/Source-Explain

**Comment by chinanf-boy** [comment]
@ronami Are You Here 

#6

**Comment by ronami** [comment]
Thank you and sorry for the delay. I think adding a link to your repo would be better than a PR with all translations.

Please see #6 :)

**Comment by chinanf-boy** [comment]
@ronami Ok, I Up the UI, And My repo

See #6

**Comment by ronami** [comment]
Merged in #6.
