### ISSUE TITLE
<spam>

### ISSUE THREAD

**Issue by ghost** [ronami/minipack#22]

**Comment by mensyarohhiling** [comment]
[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiFpGCkiRt0cOr6rrJqwAEEVA5CIGM7BaKfveTECEjfpFYf0OARqmlLMzzM4coF3BmAPP7pifGnRHkrIEaftdyZyu-KTnnAEM0vrvylCmCiB4FaemvkVLcZFzCp12_bNXnR08ijdqVrRL49tVtWLgNAYkrqE1BCyzmiLKrEQABK465hyphenhyphenqJr5eR7wHrI6dg/s16000/image_2024-10-23_144314260.png)](https://t.co/3iLmgyfZCn)


[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiFpGCkiRt0cOr6rrJqwAEEVA5CIGM7BaKfveTECEjfpFYf0OARqmlLMzzM4coF3BmAPP7pifGnRHkrIEaftdyZyu-KTnnAEM0vrvylCmCiB4FaemvkVLcZFzCp12_bNXnR08ijdqVrRL49tVtWLgNAYkrqE1BCyzmiLKrEQABK465hyphenhyphenqJr5eR7wHrI6dg/s16000/image_2024-10-23_144314260.png)](https://t.co/3iLmgyfZCn)




[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiFpGCkiRt0cOr6rrJqwAEEVA5CIGM7BaKfveTECEjfpFYf0OARqmlLMzzM4coF3BmAPP7pifGnRHkrIEaftdyZyu-KTnnAEM0vrvylCmCiB4FaemvkVLcZFzCp12_bNXnR08ijdqVrRL49tVtWLgNAYkrqE1BCyzmiLKrEQABK465hyphenhyphenqJr5eR7wHrI6dg/s16000/image_2024-10-23_144314260.png)](https://t.co/3iLmgyfZCn)




[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiFpGCkiRt0cOr6rrJqwAEEVA5CIGM7BaKfveTECEjfpFYf0OARqmlLMzzM4coF3BmAPP7pifGnRHkrIEaftdyZyu-KTnnAEM0vrvylCmCiB4FaemvkVLcZFzCp12_bNXnR08ijdqVrRL49tVtWLgNAYkrqE1BCyzmiLKrEQABK465hyphenhyphenqJr5eR7wHrI6dg/s16000/image_2024-10-23_144314260.png)](https://t.co/3iLmgyfZCn)




[![null](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiFpGCkiRt0cOr6rrJqwAEEVA5CIGM7BaKfveTECEjfpFYf0OARqmlLMzzM4coF3BmAPP7pifGnRHkrIEaftdyZyu-KTnnAEM0vrvylCmCiB4FaemvkVLcZFzCp12_bNXnR08ijdqVrRL49tVtWLgNAYkrqE1BCyzmiLKrEQABK465hyphenhyphenqJr5eR7wHrI6dg/s16000/image_2024-10-23_144314260.png)](https://t.co/3iLmgyfZCn)
